name: Make docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: portaudio19-dev rabbitmq-server

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Deploy docs to ghpages
        run: uv run mkdocs gh-deploy --force
